name: Add rock version

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The major.minor (or full) version to onboard, e.g. '0.34'"
        required: true
        type: string

jobs:
  add-version:
    name: Add rock version
    uses: canonical/observability/.github/workflows/rock-add-version.yaml@v2
    secrets: inherit
    with:
      source-repo: prometheus/alertmanager
      version: ${{ inputs.version }}
