name: Build ROCK

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup LXD
      uses: whywaita/setup-lxd@v1
      with:
        lxd_version: latest/stable

    - name: Install dependencies
      run: |
        sudo snap install yq
        sudo snap install --classic --channel edge rockcraft
        sudo iptables -F FORWARD
        sudo iptables -P FORWARD ACCEPT

    - name: Build ROCK
      run: rockcraft pack --verbose

    - name: Upload ROCK to ghcr.io
      run: |
        VERSION=$(yq -r '.version' rockcraft.yaml)
        sudo skopeo --insecure-policy copy oci-archive:$(realpath ./alertmanager_*.rock) docker://ghcr.io/canonical/alertmanager:$VERSION --dest-creds "${{ secrets.GHCR_USERNAME }}:${{ secrets.GHCR_PASSWORD }}"

    - name: Install Syft
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

    - name: Create SBOM
      run: syft $(realpath ./alertmanager_*.rock) -o spdx-json=alertmanager.sbom.json

    - name: Upload SBOM
      uses: actions/upload-artifact@v3
      with:
        name: alertmanager-sbom
        path: "alertmanager.sbom.json"
    - name: Upload locally built ROCK artifact
      uses: actions/upload-artifact@v3
      with:
        name: alertmanager-rock
        path: "alertmanager_*.rock"
