name: Check for new alertmanager releases

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0,4,8,12,16,20 * * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  check:
    name: Detect new releases
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo snap install yq

      - id: latest-release
        uses: pozetroninc/github-action-get-latest-release@v0.6.0
        with:
          repository: prometheus/alertmanager
          excludes: prerelease, draft

      - name: Checkout the ROCK source
        uses: actions/checkout@v3
        with:
          path: main

      - id: check
        name: Check for new releases
        shell: bash
        run: |
          release=$(yq '.parts.alertmanager["source-tag"]' $GITHUB_WORKSPACE/main/rockcraft.yaml)
          if [ "${release}" != "${{steps.latest-release.outputs.release}}" ]; then
            echo "release=${{steps.latest-release.outputs.release}}" >> $GITHUB_OUTPUT
            echo "New upstream release ${{steps.latest-release.outputs.release}} found"
          else
            echo "No new upstream release found"
          fi

      - id: alertmanager-go-version
        name: Checkout alertmanager source (to get recommended go version)
        uses: actions/checkout@v3
        with:
          repository: prometheus/alertmanager
          ref: ${{steps.check.outputs.release}}
          path: alertmanager-src

      - name: Update the version file and push a branch
        if: ${{ steps.check.outputs.release != '' }}
        shell: bash
        run: |
          source_tag="${{steps.check.outputs.release}}" \
          version=${source_tag#"v"} \
          go_version=$(grep -Po "^go \K(\S+)" $GITHUB_WORKSPACE/alertmanager-src/go.mod) \
          yq -i '.version = strenv(version) | .parts.alertmanager["source-tag"] = strenv(source_tag) | .parts.alertmanager["build-snaps"] = ["go/" + strenv(go_version) + "/stable"]' $GITHUB_WORKSPACE/main/rockcraft.yaml

      - name: Create a PR
        if: ${{ steps.check.outputs.release != '' }}
        uses: peter-evans/create-pull-request@v4.2.3
        with:
          path: main
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(deps): bump alertmanager version to ${{ steps.check.outputs.release }}"
          committer: "Github Actions <github-actions@github.com>"
          author: "Github Actions <github-actions@github.com>"
          title: "Update to Alertmanager ${{ steps.check.outputs.release }}"
          body: Automated update to follow upstream [release](https://github.com/prometheus/alertmanager/releases/tag/${{ steps.check.outputs.release }}) of Alertmanager.
          branch: "chore/bump-version-to-${{ steps.check.outputs.release }}"
          delete-branch: true
