name: "Publish rock to GHCR:dev"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  build:
    uses: canonical/observability/.github/workflows/rock-release-dev.yaml@v0
    secrets: inherit
    with:
      rock-name: alertmanager
