name: Open a PR to OCI Factory

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: canonical/observability/.github/workflows/rock-release-oci-factory.yaml@feature/release-oci-factory
    with:
      rock-name: alertmanager
